### ISSUE TITLE
do you still need to manually download data?

### ISSUE THREAD

**Issue by andrewharvey** [geogeeks-au/MainRoads-to-OSM#10]
>Download RoadNetworkMRWA_514.zip from >http://catalogue.beta.data.wa.gov.au/dataset/ntwk-iris-road-network (Keith says it is >possible to get download this from the command-line, but it's tricky.) This dataset was last >updated 2016-04-11.

Did you end up solving this with https://github.com/geogeeks-au/MainRoads-to-OSM/blob/master/mrwa2osm.sh#L8 ?

I managed to automate it here https://github.com/andrewharvey/mainroadswa4osm/blob/master/index.js by automating the SSO page login.

**Comment by samwilson** [comment]
Yep, the downloading works now. We don't have the cronjob running any more though. But yeah, the Basic Auth in that script was functioning. :)

**Comment by keithamoss** [comment]
Hi Andrew,

Yeah, we ended up solving it - though the issue that Sam had in this case was special characters in the password needing to be escaped because bash.

You can make the auth dance a little nicer if you pass "SLIPAppUser" as the User-Agent header, provide the username/password as per HTTP Basic Auth, and follow the 403 redirects you'll get sent.

The gory details are discussed here in case you've not seen it: https://toolkit.data.wa.gov.au/hc/en-gb/articles/115000962734-How-To-Download-Geospatial-Data-Snapshots

Check out the Python example at the bottom for the cleanest implementation.

**Comment by andrewharvey** [comment]
> https://toolkit.data.wa.gov.au/hc/en-gb/articles/115000962734-How-To-Download-Geospatial-Data-Snapshots

I wish I had seen that before! Thanks @keithamoss
